version: "3.8"

services:
  db:
    image: postgres:15.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: moviedb