package pt.xpandit.movieapi.dto.request;

import jakarta.validation.constraints.*;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Represents a request to create or update a movie.
 *
 * @param title      The title of the movie.
 * @param launchDate The launch date of the movie.
 * @param rank       The ranking of the movie.
 * @param revenue    The revenue generated by the movie.
 */
public record MovieRequest(
    @NotBlank(message = "The title is required")
    String title,

    @NotNull(message = "The launch date is required")
    LocalDate launchDate,

    @NotNull(message = "The rank is required")
    @DecimalMin(value = "0.0", message = "Rank must be between 0 and 10")
    @DecimalMax(value = "10.0", message = "Rank must be between 0 and 10")
    BigDecimal rank,

    @NotNull(message = "The revenue is required")
    @PositiveOrZero(message = "Revenue must be zero or positive")
    BigDecimal revenue
) {}
